# выбрасывал ошибку 'Usage Error: Unrecognized or legacy configuration settings found' при выполнении yarn dlx shadcn@latest add ...
# approvedGitRepositories:
#   - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0
