import { writeFile } from 'node:fs/promises';
import path from 'node:path';

import type { DisciplineManifest } from '../../src/shared/lib/content/schemas/discipline.js';
import { paths } from './paths.js';

export type CatalogRole = {
  id: string;
  label: string;
  stacks: Array<{ id: string; label: string; available: boolean }>;
};

export function manifestsToCatalogRoles(manifests: DisciplineManifest[]): CatalogRole[] {
  return manifests.map((manifest) => ({
    id: manifest.roleId,
    label: manifest.title,
    stacks: manifest.stacks.map((stack) => ({
      id: stack.id,
      label: stack.label,
      available: stack.available === true,
    })),
  }));
}

export function formatDisciplineCatalogTs(roles: CatalogRole[]): string {
  return `/** Generated by yarn content:compile from .courses/<role>/discipline.yaml. Do not edit. */

export const GENERATED_DISCIPLINE_ROLES = ${JSON.stringify(roles, null, 2)} as const;
`;
}

/** Write committed catalog snapshot so UI matches local discipline.yaml. */
export async function writeDisciplineCatalog(manifests: DisciplineManifest[]): Promise<string> {
  const outPath = path.join(paths.generatedDir, 'disciplines.ts');
  const source = formatDisciplineCatalogTs(manifestsToCatalogRoles(manifests));
  await writeFile(outPath, source, 'utf8');
  return outPath;
}
